### ISSUE TITLE
do you have live website & demo?

### ISSUE THREAD

**Issue by hbakhtiyor** [wilcommerce/Wilcommerce.Core#26]
hey,

if have, would be nice to add to [rank platform](https://www.ecommwar.com)

**Comment by albx** [comment]
Hi, up to now I'm still working on the core libraries so I haven't any demo yet.
Wilcommerce will be an Ecommerce framework, so I'm not focused on the web part at this moment.

wilcommerce.com will be updated with the list of available package as soon as I finish the catalog part (i.e. components, persistence and web components in asp.net core).

Thank you!
